### ISSUE TITLE
Cannot Start Container error

### ISSUE THREAD

**Issue by fxdgear** [nicgrayson/dockerfiles#1]
```
Cannot start container 6cf3057753a4207583e7c662a987d5b4a6ddac38a48d4194cd666d112ee96f35: setup mount namespace create device nodes mknod /dev/fuse operation not permitted
```

I'm following your blog post here: http://nicgrayson.com/docker-local-dev/
BUT I'm getting an error when trying to start the DNS container.

**Comment by fxdgear** [comment]
I deleted all containers, and the image, re pulled and added the `CMD` from the docker file to the `command` key in the fig file and it's working.

**Comment by nicgrayson** [comment]
Strange. You shouldn't have to do that. Let me know if you have any more issues.
